/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SellingRouteImport } from './routes/selling'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminTeamRouteImport } from './routes/admin-team'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellingIndexRouteImport } from './routes/selling.index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as TeamSlugRouteImport } from './routes/team.$slug'
import { Route as SellingUpsellsRouteImport } from './routes/selling.upsells'
import { Route as SellingSettingsRouteImport } from './routes/selling.settings'
import { Route as SellingProductsRouteImport } from './routes/selling.products'
import { Route as SellingCrossSellsRouteImport } from './routes/selling.cross-sells'
import { Route as SellingBundlesRouteImport } from './routes/selling.bundles'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as ConfirmOrderIdRouteImport } from './routes/confirm-order.$id'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as ApiPublicPaymobWebhookRouteImport } from './routes/api/public/paymob-webhook'
import { Route as ApiPublicPaymobCallbackRouteImport } from './routes/api/public/paymob.callback'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SellingRoute = SellingRouteImport.update({
  id: '/selling',
  path: '/selling',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin-team',
  path: '/admin-team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellingIndexRoute = SellingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellingRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TeamRoute,
} as any)
const SellingUpsellsRoute = SellingUpsellsRouteImport.update({
  id: '/upsells',
  path: '/upsells',
  getParentRoute: () => SellingRoute,
} as any)
const SellingSettingsRoute = SellingSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SellingRoute,
} as any)
const SellingProductsRoute = SellingProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellingRoute,
} as any)
const SellingCrossSellsRoute = SellingCrossSellsRouteImport.update({
  id: '/cross-sells',
  path: '/cross-sells',
  getParentRoute: () => SellingRoute,
} as any)
const SellingBundlesRoute = SellingBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => SellingRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => PaymentRoute,
} as any)
const ConfirmOrderIdRoute = ConfirmOrderIdRouteImport.update({
  id: '/confirm-order/$id',
  path: '/confirm-order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymobWebhookRoute = ApiPublicPaymobWebhookRouteImport.update({
  id: '/api/public/paymob-webhook',
  path: '/api/public/paymob-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymobCallbackRoute = ApiPublicPaymobCallbackRouteImport.update({
  id: '/api/public/paymob/callback',
  path: '/api/public/paymob/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-team': typeof AdminTeamRoute
  '/cart': typeof CartRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRouteWithChildren
  '/payment-success': typeof PaymentSuccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/selling': typeof SellingRouteWithChildren
  '/shop': typeof ShopRoute
  '/team': typeof TeamRouteWithChildren
  '/categories/$slug': typeof CategoriesSlugRoute
  '/confirm-order/$id': typeof ConfirmOrderIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/product/$id': typeof ProductIdRoute
  '/selling/bundles': typeof SellingBundlesRoute
  '/selling/cross-sells': typeof SellingCrossSellsRoute
  '/selling/products': typeof SellingProductsRoute
  '/selling/settings': typeof SellingSettingsRoute
  '/selling/upsells': typeof SellingUpsellsRoute
  '/team/$slug': typeof TeamSlugRoute
  '/categories/': typeof CategoriesIndexRoute
  '/selling/': typeof SellingIndexRoute
  '/api/public/paymob-webhook': typeof ApiPublicPaymobWebhookRoute
  '/api/public/paymob/callback': typeof ApiPublicPaymobCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-team': typeof AdminTeamRoute
  '/cart': typeof CartRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRouteWithChildren
  '/payment-success': typeof PaymentSuccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/team': typeof TeamRouteWithChildren
  '/categories/$slug': typeof CategoriesSlugRoute
  '/confirm-order/$id': typeof ConfirmOrderIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/product/$id': typeof ProductIdRoute
  '/selling/bundles': typeof SellingBundlesRoute
  '/selling/cross-sells': typeof SellingCrossSellsRoute
  '/selling/products': typeof SellingProductsRoute
  '/selling/settings': typeof SellingSettingsRoute
  '/selling/upsells': typeof SellingUpsellsRoute
  '/team/$slug': typeof TeamSlugRoute
  '/categories': typeof CategoriesIndexRoute
  '/selling': typeof SellingIndexRoute
  '/api/public/paymob-webhook': typeof ApiPublicPaymobWebhookRoute
  '/api/public/paymob/callback': typeof ApiPublicPaymobCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-team': typeof AdminTeamRoute
  '/cart': typeof CartRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRouteWithChildren
  '/payment-success': typeof PaymentSuccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/selling': typeof SellingRouteWithChildren
  '/shop': typeof ShopRoute
  '/team': typeof TeamRouteWithChildren
  '/categories/$slug': typeof CategoriesSlugRoute
  '/confirm-order/$id': typeof ConfirmOrderIdRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/product/$id': typeof ProductIdRoute
  '/selling/bundles': typeof SellingBundlesRoute
  '/selling/cross-sells': typeof SellingCrossSellsRoute
  '/selling/products': typeof SellingProductsRoute
  '/selling/settings': typeof SellingSettingsRoute
  '/selling/upsells': typeof SellingUpsellsRoute
  '/team/$slug': typeof TeamSlugRoute
  '/categories/': typeof CategoriesIndexRoute
  '/selling/': typeof SellingIndexRoute
  '/api/public/paymob-webhook': typeof ApiPublicPaymobWebhookRoute
  '/api/public/paymob/callback': typeof ApiPublicPaymobCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/admin-team'
    | '/cart'
    | '/forgot-password'
    | '/login'
    | '/payment'
    | '/payment-success'
    | '/reset-password'
    | '/selling'
    | '/shop'
    | '/team'
    | '/categories/$slug'
    | '/confirm-order/$id'
    | '/payment/callback'
    | '/product/$id'
    | '/selling/bundles'
    | '/selling/cross-sells'
    | '/selling/products'
    | '/selling/settings'
    | '/selling/upsells'
    | '/team/$slug'
    | '/categories/'
    | '/selling/'
    | '/api/public/paymob-webhook'
    | '/api/public/paymob/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/admin-team'
    | '/cart'
    | '/forgot-password'
    | '/login'
    | '/payment'
    | '/payment-success'
    | '/reset-password'
    | '/shop'
    | '/team'
    | '/categories/$slug'
    | '/confirm-order/$id'
    | '/payment/callback'
    | '/product/$id'
    | '/selling/bundles'
    | '/selling/cross-sells'
    | '/selling/products'
    | '/selling/settings'
    | '/selling/upsells'
    | '/team/$slug'
    | '/categories'
    | '/selling'
    | '/api/public/paymob-webhook'
    | '/api/public/paymob/callback'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/admin-team'
    | '/cart'
    | '/forgot-password'
    | '/login'
    | '/payment'
    | '/payment-success'
    | '/reset-password'
    | '/selling'
    | '/shop'
    | '/team'
    | '/categories/$slug'
    | '/confirm-order/$id'
    | '/payment/callback'
    | '/product/$id'
    | '/selling/bundles'
    | '/selling/cross-sells'
    | '/selling/products'
    | '/selling/settings'
    | '/selling/upsells'
    | '/team/$slug'
    | '/categories/'
    | '/selling/'
    | '/api/public/paymob-webhook'
    | '/api/public/paymob/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AdminTeamRoute: typeof AdminTeamRoute
  CartRoute: typeof CartRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PaymentRoute: typeof PaymentRouteWithChildren
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellingRoute: typeof SellingRouteWithChildren
  ShopRoute: typeof ShopRoute
  TeamRoute: typeof TeamRouteWithChildren
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ConfirmOrderIdRoute: typeof ConfirmOrderIdRoute
  ProductIdRoute: typeof ProductIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ApiPublicPaymobWebhookRoute: typeof ApiPublicPaymobWebhookRoute
  ApiPublicPaymobCallbackRoute: typeof ApiPublicPaymobCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selling': {
      id: '/selling'
      path: '/selling'
      fullPath: '/selling'
      preLoaderRoute: typeof SellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-team': {
      id: '/admin-team'
      path: '/admin-team'
      fullPath: '/admin-team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selling/': {
      id: '/selling/'
      path: '/'
      fullPath: '/selling/'
      preLoaderRoute: typeof SellingIndexRouteImport
      parentRoute: typeof SellingRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof TeamRoute
    }
    '/selling/upsells': {
      id: '/selling/upsells'
      path: '/upsells'
      fullPath: '/selling/upsells'
      preLoaderRoute: typeof SellingUpsellsRouteImport
      parentRoute: typeof SellingRoute
    }
    '/selling/settings': {
      id: '/selling/settings'
      path: '/settings'
      fullPath: '/selling/settings'
      preLoaderRoute: typeof SellingSettingsRouteImport
      parentRoute: typeof SellingRoute
    }
    '/selling/products': {
      id: '/selling/products'
      path: '/products'
      fullPath: '/selling/products'
      preLoaderRoute: typeof SellingProductsRouteImport
      parentRoute: typeof SellingRoute
    }
    '/selling/cross-sells': {
      id: '/selling/cross-sells'
      path: '/cross-sells'
      fullPath: '/selling/cross-sells'
      preLoaderRoute: typeof SellingCrossSellsRouteImport
      parentRoute: typeof SellingRoute
    }
    '/selling/bundles': {
      id: '/selling/bundles'
      path: '/bundles'
      fullPath: '/selling/bundles'
      preLoaderRoute: typeof SellingBundlesRouteImport
      parentRoute: typeof SellingRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof PaymentRoute
    }
    '/confirm-order/$id': {
      id: '/confirm-order/$id'
      path: '/confirm-order/$id'
      fullPath: '/confirm-order/$id'
      preLoaderRoute: typeof ConfirmOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paymob-webhook': {
      id: '/api/public/paymob-webhook'
      path: '/api/public/paymob-webhook'
      fullPath: '/api/public/paymob-webhook'
      preLoaderRoute: typeof ApiPublicPaymobWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paymob/callback': {
      id: '/api/public/paymob/callback'
      path: '/api/public/paymob/callback'
      fullPath: '/api/public/paymob/callback'
      preLoaderRoute: typeof ApiPublicPaymobCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PaymentRouteChildren {
  PaymentCallbackRoute: typeof PaymentCallbackRoute
}

const PaymentRouteChildren: PaymentRouteChildren = {
  PaymentCallbackRoute: PaymentCallbackRoute,
}

const PaymentRouteWithChildren =
  PaymentRoute._addFileChildren(PaymentRouteChildren)

interface SellingRouteChildren {
  SellingBundlesRoute: typeof SellingBundlesRoute
  SellingCrossSellsRoute: typeof SellingCrossSellsRoute
  SellingProductsRoute: typeof SellingProductsRoute
  SellingSettingsRoute: typeof SellingSettingsRoute
  SellingUpsellsRoute: typeof SellingUpsellsRoute
  SellingIndexRoute: typeof SellingIndexRoute
}

const SellingRouteChildren: SellingRouteChildren = {
  SellingBundlesRoute: SellingBundlesRoute,
  SellingCrossSellsRoute: SellingCrossSellsRoute,
  SellingProductsRoute: SellingProductsRoute,
  SellingSettingsRoute: SellingSettingsRoute,
  SellingUpsellsRoute: SellingUpsellsRoute,
  SellingIndexRoute: SellingIndexRoute,
}

const SellingRouteWithChildren =
  SellingRoute._addFileChildren(SellingRouteChildren)

interface TeamRouteChildren {
  TeamSlugRoute: typeof TeamSlugRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamSlugRoute: TeamSlugRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AdminTeamRoute: AdminTeamRoute,
  CartRoute: CartRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PaymentRoute: PaymentRouteWithChildren,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SellingRoute: SellingRouteWithChildren,
  ShopRoute: ShopRoute,
  TeamRoute: TeamRouteWithChildren,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ConfirmOrderIdRoute: ConfirmOrderIdRoute,
  ProductIdRoute: ProductIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ApiPublicPaymobWebhookRoute: ApiPublicPaymobWebhookRoute,
  ApiPublicPaymobCallbackRoute: ApiPublicPaymobCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
